language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update
  - if [[ -n $PACKAGIST_TOKEN ]]; then composer config http-basic.repo.packagist.com token $PACKAGIST_TOKEN; fi

install:
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)